site_name: Guidelines
nav:
  - Introduction: index.md
  - Introduction: index.fr.md
  - FGP Authoring Tool: authortool.md
  - FGP Authoring Tool: authortool.fr.md
  - Choosing The Right Plugin: chooseplugins.md
  - Choosing The Right Plugin: chooseplugins.fr.md
  - Configuring Plugins for Time-Series Visualization:
    - Range Slider: ./plugins/range.md
    - Range Slider: ./plugins/range.fr.md
    - Thematic Slider: ./plugins/thematic.md
    - Thematic Slider: ./plugins/thematic.fr.md
    - Charting Tools: ./plugins/charting.md
    - Charting Tools: ./plugins/charting.fr.md
    - Swiper: ./plugins/swiper.md
    - Swiper: ./plugins/swiper.fr.md
  - Other Plugins:
    - Area of Interest: ./plugins/aoi.md
    - Area of Interest: ./plugins/aoi.fr.md
    - Coordinates Info Plugin: ./plugins/coord.md
    - Coordinates Info Plugin: ./plugins/coord.fr.md
    - Draw Toolbar: ./plugins/draw.md
    - Draw Toolbar: ./plugins/draw.fr.md

theme:
  name: material
  font:
    text: Ubuntu
  features:
    - toc.integrate

    - navigation.tabs.sticky
    - navigation.sections

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition

extra_javascript:
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        fr: en français
      translate_nav:
        fr: 
          Introduction: "Introduction"
          FGP Authoring Tool: "Outil de création de FGP "
          Choosing The Right Plugin: "Choisir le bon plugin"
          Configuring Plugins for Time-Series Visualization: "Configuration des plugins pour la visualisation des séries temporelles"
          Range Slider: Curseur de plage
          Thematic Slider: Curseur de plage thematique
          Charting Tools: Graphiques
          Swiper: Gilsseur
          Other Plugins: Autres plugins 
          Area of Interest: Regions d'interet
          Coordinates Info Plugin: Info coordonnees
          Draw Toolbar: Barre de dessin
